project_id = "eohnperxrykjzoofhfqu"

[functions.suggest-category]
verify_jwt = false

[functions.financial-insights]
verify_jwt = false

[functions.weekly-summary]
verify_jwt = false

[functions.monthly-summary]
verify_jwt = false
